---
title: "8. 제주도 관광객 몰린 곳은"
output: html_notebook
---


```{r}
t<-read.csv('data/2015-08-jeju.csv', header=TRUE)
str(t)

t$daylight <- t$X10시.11시.유동인구 + t$X11시.12시.유동인구 + t$X12시.13시.유동인구 + t$X12시.13시.유동인구 + t$X14시.15시.유동인구 + t$X15시.16시.유동인구 + t$X16시.17시.유동인구 + t$X17시.18시.유동인구 + t$X18시.19시.유동인구 + t$X19시.20시.유동인구

t2<-subset(t[order(-t$daylight), ][1:100,], select=c('daylight', '지번명'))

str(t2)



```


한국 주소를 입력하면 위도와 경도를 알려주는 함수 : mutate_geocode()

ggmap 패키지에 들어 있음.

utf8 문자열 형식으로 되어 있어야 함.

```{r}
install.packages('ggmap')
library(ggmap)


# ggmap 2.7을 설치합니다. (아직 CRAN에 등록되어 있지 않습니다.)
devtools::install_github('dkahle/ggmap')
library(ggmap)

t2$addr<-enc2utf8(as.character(t2$지번명))
str(t2)

register_google(key="AIzaSyBUFrKDpobNTCSTxrj0hP0RjAM5U6d6HVw")

t3<-mutate_geocode(t2, addr, source='google')

str(t3)
unique(t3$lon)

#?register_google
```


구글 정책이 바뀌어서 mutate_geocode() 를 바로 사용할수가 없다.
http://cloud.google.com/maps-platform/ 

에 접속한 후에, API key를 받아야 한다.

받은 API Key를 mutate_geocode() 사용 전에

register_google(key="API Key") 로 등록을 해야한다.

geocode는 돈을 내라고 하는데, 

평가판 300 크레딧으로 쓴건지? 되고 있음. 

#########################################

leaflet 패키지로 경도,위도 정보를 지도에 표현하기
leaflet 패키지는 지도 패키지 임.

```{r}
install.packages('leaflet')

library(leaflet)

m<-leaflet()
m<-addProviderTiles(m, providers$OpenStreeMap)
m<-setView(m, lat=33.3616670, lng = 126.5291670, zoom=11)
m

m<-leaflet(data=t3)
m<-setView(m, lat=33.3616670, lng = 126.5291670, zoom=11)
m<-addProviderTiles(m, providers$OpenStreeMap)
m<-addCircles(m, lng=~lon, lat=~lat, radius=~daylight/5)
m


```



```{r}
library(leaflet)
library(ggmap)

register_google(key="AIzaSyBUFrKDpobNTCSTxrj0hP0RjAM5U6d6HVw")
somePlace <- ggmap::geocode("Jeju")  
# Information from URL : http://maps.googleapis.com/maps/api/geocode/json?       address=Vienna&sensor=false  

somePlace$lon=126.5291670
somePlace$lat=33.3616670
somePlace

#   lon      lat
# 1 16.37382 48.20817

leaflet(somePlace) %>% addTiles() %>% addMarkers() %>%
  addCircles(lng = t3$lon, lat=t3$lat, radius=t3$daylight/5) 
```






